name: CI Checks

on:
  push:
    branches:
      - main
      - "release**"
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  test_on_linux:
    name: build (ubuntu, py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_URI: postgresql://user:password@localhost:5432/testdb

    steps:
      # same steps here (checkout, setup Python, install, pytest, codecov)

  test_on_mac_win:
    name: build (${{ matrix.os }}, py3.13)
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [windows, macos]

    env:
      POSTGRES_URI: postgresql://user:password@localhost:5432/testdb

    steps:
      # checkout, setup Python, install

      - name: Install PostgreSQL (Windows)
        if: matrix.os == 'windows'
        run: |
          choco install postgresql15 --params '/Password:password' -y
          echo "C:\Program Files\PostgreSQL\15\bin" >> $GITHUB_PATH

      - name: Init and Start PostgreSQL (Windows)
        if: matrix.os == 'windows'
        run: |
          initdb -D pgdata
          pg_ctl -D pgdata -l logfile start
          createdb -U postgres testdb

      - name: Install PostgreSQL (macOS)
        if: matrix.os == 'macos'
        run: |
          brew install postgresql@15
          brew services start postgresql@15
          sleep 5
          createdb testdb

      - name: Test with pytest
        run: pytest --durations=10 --cov=mesa_frames tests/ --cov-report=xml

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [test_on_linux, test_on_mac_win]
    steps:
      - run: echo "All matrix jobs completed successfully."
